#!/bin/bash

nc -l 6543 > out.txt &
sleep 1
./null_tunnel.py -llocalhost:6544 -flocalhost:6543 &
sleep 1
echo "Secret Message" | nc localhost 6544
#kill -9 `pgrep nc`
#kill -9 `pgrep -f null_tunnel`
echo "out.txt's content:"
cat out.txt